### ISSUE TITLE
All contacts not showing in drop down

### ISSUE THREAD

**Issue by FilipinaW** [ringcentral/rc-unified-crm-extension#2]
I have a weird behaviour right now.  One of our organization has 8 contacts with the same phone number (they only use main number).  Extension is showing only one name with no drop down to choose a different name.  Also, the contact name showing in the history changed throughout the day, is was a different person earlier on today then it is showing now.

**Comment by DaKingKong** [comment]
@FilipinaW It's an interesting use case. Firstly, it's a design decision to avoid showing multiple Pipedrive contacts for one number (the previous issue that you saw was 1 Pipedrive number and 1 RC Extension number).

The design decision is definitely open to changes. Would you mind giving me some more details on your use case of 8 contacts with the same number? Some of the questions that I can think of are:

1. What's the difference between having 8 contact and just 1 contact as the entity that those contacts belong to?
2. How is the call log process handled? Get the contact name from the call, and then find it by name rather than number?  

Feel free to email me on da.kong@ringcentral.com if you prefer.
